enum StateEnum {
    SELECT_CARDS_STATE = "SELECT_CARDS_STATE",
    SELECT_COLUMN_TO_PLAY_STATE = "SELECT_COLUMN_TO_PLAY_STATE",
    DISCARD_CARDS_FROM_HAND_STATE = "DISCARD_CARDS_FROM_HAND_STATE",
}

export default StateEnum
